{% set name = "simplegmail" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simplegmail-{{ version }}.tar.gz
  sha256: 37e527366d0c54e64ce9e2f1d3e4cdb53247ea40d30564dea371f40cf09ca135
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - beautifulsoup4
    - google-api-python-client >=1.7.3
    - lxml >=4.4.2
    - oauth2client >=4.1.3
    - python >=3.6
    - python-dateutil >=2.8.1

test:
  imports:
    - simplegmail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jeremyephron/simplegmail
  summary: A simple Python API client for Gmail.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
